### ISSUE TITLE
Need the feature tap on a part string

### ISSUE THREAD

**Issue by nttra83** [svdo/swift-RichText#2]
Hello,
This is good library. Thank you so much :).
Could you implement the feature tap on a part string?
Thanks in advance,

**Comment by markspanbroek** [comment]
Hi @nttra83, glad to hear that you're enjoying the library.

This library revolves around making attributed strings. You can then pass those to e.g. a UILabel to display. The UILabel then takes care of rendering the string and reacting to any taps or other gestures. So this library is probably not the right place to implement support for tapping on a string.

But luckily there are other libraries that extend UILabel to support tapping on a substring. For instance: https://github.com/null09264/FRHyperLabel.

**Comment by svdo** [comment]
Thanks @nttra83 :) I agree with @markspanbroek's answer. Note though that you can actually make a hyperlink inside an attributed string using this library (see https://github.com/svdo/swift-RichString#linkurl and https://github.com/svdo/swift-RichString#linkstring). Depending on the user experience you're looking for, that may also be an option.

**Comment by nttra83** [comment]
Thanks @svdo, @markspanbroek,
I agree with @markspanbroek's answer too.
FRHyperLabel is so good :).
